# swagger2
swagger2.package: cn.shop.portal.controller

#配置模板想到classpath路径，后面须加上"/"
beetl:
  templates-path: templates/
  config:
    html-tag-flag: true

#配置模板的后缀，自动读取spring.mvc.view.suffix
spring:
  mvc:
    view:
      suffix: .html
  redis:
    host: 47.107.92.79
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
# 广告Cid
big_ad_index: 1

#商品服务器
item_path: http://localhost:8104/




