spring:
  ##数据库连接信息
  datasource:
     url: jdbc:mysql://47.107.92.79:3306/microshop?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
     type: com.alibaba.druid.pool.DruidDataSource
     username: microshop
     password: "Microshop123."
     password_encrypted: "true"
     driverClassName: com.mysql.jdbc.Driver
     maxActive: 30
     minIdle : 10
     maxWait: 1000
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 20
     keepAlive: true
     minEvictableIdleTimeMillis: 60000
     validationQuery: "SELECT 'x'"
     testWhileIdle: true
     filters: "stat"

mybatis:
    type-aliases-package: com.shop.pojo
    mapper-locations: classpath:mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# swagger2
swagger2.package: com.shop.item.service

# Redis
redisKey:
  # 缓存时间 默认半小时
  expire_time: 1800
  prefix:
    # 用户登录信息前缀
    user_session: 'USER_SESSION:'
    # 验证码Redis前缀
    verifycode: 'VERIFYCODE:'
    # 号码code
    mobile_login_code: 'MOBILE_LOGIN_CODE:'

login:
  # 验证名
  validation:
    #登录名
    ispinengaged: isPinEngaged
    #邮箱
    isemailengaged: isEmailEngaged
    #手机
    ismobileengaged: isMobileEngaged
  # 推荐登录名后缀随机数取值范围
  random_number: 50000
  # 登录成功页面
  success_url: http://localhost:8104/success